version: "2"
services:
  web:
    # image: webdevops/php-nginx:7.4
    build: .
    volumes:
      - ./:/app
    ports:
      - 8088:80
    environment:
      WEB_DOCUMENT_ROOT: /app
      PHP_DATE_TIMEZONE: Asia/Bangkok
      PHP_MEMORY_LIMIT: 2560M
      PHP_MAX_EXECUTION_TIME: 180
      FPM_RLIMIT_FILES: 1000000
      FPM_MAX_REQUESTS: 1000
      FPM_PM_START_SERVERS: 60
      FPM_PM_MIN_SPARE_SERVERS: 30
      FPM_PM_MAX_SPARE_SERVERS: 60
      FPM_REQUEST_TERMINATE_TIMEOUT: 180
      FPM_PM_MAX_CHILDREN: 60
    depends_on:
      - mariadb
  memcache:
    image: memcached:1.5

  mariadb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    environment:
      - MARIADB_ROOT_PASSWORD=1q2w3e4r
      - MARIADB_DATABSE=mwa_db
      - MARIADB_USER=devtest
      - MARIADB_PASSWORD=1q2w3e4r
      - MARIADB_HOST=localhost
    volumes:
      - "mariadb_data:/bitnami"
  phpmyadmin:
    image: "docker.io/bitnami/phpmyadmin:5-debian-10"
    environment:
      UPLOAD_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 2G
      PHP_POST_MAX_SIZE: 2G
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
